### ISSUE TITLE
Setup a development server

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#121]
When we release PP 0.2 to the first users, our current server will be used in production and we need another for development.

**Comment by glowka** [comment]
Done, I alos moved current prod deployment from America to EU data centre (for better ping) by copying the deployment, so @kaglowka  the stale one `damp-headland-12387` can be deleted. Please also accept ownership transfer of new `pp-prod` and `pp-dev1` heroku apps as I created them and until your acceptance they belong to me.
