### ISSUE TITLE
Annotation mode and disabled extension mode interaction

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#124]
A bunch of basic questions.
- should it be possible to turn on the annotation mode when in the disabled extension mode?
- should an already open Editor disappear when the extension is disabled?
- should an already open Editor disappear when the annotation mode is turned off?

Add your own if anything more comes to your mind.

**Comment by KasiaSkowronska** [comment]
- no
- yes
- yes

Also I think it would be nice to handle this scenario when user first highlights text and then clicks "dodaj przypis" -- in that case the Editor should open. Now it doesn't work like that and user has to highlight text twice.

**Comment by kaglowka** [comment]
I opened an issue for the scenario you mentioned. #142
