### ISSUE TITLE
Finish the browser popup

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#126]
After  #108, we need to refine the 

- [ ] grayed out icon(s)
- [ ] what to do with the "poproś o przypis" button?
- [ ] what to do with "daj znać co myślisz" button?

**Comment by KasiaSkowronska** [comment]
I suggest we add tooltip to "poproś o przypis" and "daj znać co myślisz" buttons with something like "Opcja jeszcze niedostępna w tej wersji" and make them disabled. If you would like to know why I think it's better solution then removing those buttons, we can talk (but also I think it's not a big deal and it may be a waste of time to discuss it).

I don't understand what is this "grayed out icon(s)" task

**Comment by kaglowka** [comment]
Does it make sense to include a button with information it's not available in this version?

**Comment by kaglowka** [comment]
Secondly, I've never seen an inactive button with a tooltip on mouse hover. Maybe just gray them out with a small static label like "Niedostępne w tej wersji".

**Comment by KasiaSkowronska** [comment]
ok, just remove them

**Comment by kaglowka** [comment]
Ok. Never mind the "grayed out" point. It's not necessary.
