### ISSUE TITLE
Add report and contact buttons to popup

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#231]
Analytics events included!
Name of the event: _ReportPopupClicked_

Report url: https://przypispowszechny.pl/site/report/

About us url (it will redirect to facebook for now): https://przypispowszechny.pl/site/about/

**Comment by KasiaSkowronska** [comment]
![popup](https://user-images.githubusercontent.com/23725199/48313165-a59be280-e5b8-11e8-9156-455053393a63.png)

**Comment by glowka** [comment]
Hey @KasiaSkowronska, I cannot find URL to report form (https://przypispowszechny.pl/site/report/) implemented in the related MR. Am I missing it or was it dropped along the way?

**Comment by glowka** [comment]
Same with analytics. It is quite important.

**Comment by glowka** [comment]
So to sum up, those were issues I reported above:
 - [ ] add url to report button (details in description of the task)
 - [ ] add google analytics event (details in description of the task)

-- and this is new issue I have realized just now --

- [ ] add GA event after clicking on annotation request button, proposed name _AnnotationRequestLinkClicked_


@KasiaSkowronska can take care of it?

If there are any new things, and I guess GA might be, I am here to help, so just call me. 
So to start if off: current GA events you can find in https://github.com/PrzypisPowszechny/pp-client/blob/master/src/common/pp-ga/events.ts#L86, their use isn't complicated: look for calls in the code-base. And again, if any doubts, just ask :)

**Comment by KasiaSkowronska** [comment]
ok, I'll take care of it!

**Comment by kaglowka** [comment]
Resolved in #252
