### ISSUE TITLE
Add annotation request button to popup

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#233]

**Comment by KasiaSkowronska** [comment]
![popup](https://user-images.githubusercontent.com/23725199/48313154-8ef58b80-e5b8-11e8-9484-1d57a3748b30.png)

**Comment by glowka** [comment]
I am removing "needs more details" because this issue is now about creating the button, request to API should be done in #234

**Comment by glowka** [comment]
BTW I now think that "Poproś o przypis" and "Dodaj przypis" should be a bit more important and dominating "wyłącz przypis" section.

**Comment by kaglowka** [comment]
Resolved in #242
