### ISSUE TITLE
Add annotation request saving (mail / database) on button click

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#234]

**Comment by glowka** [comment]
I added myself to assignees to provide details for "need more details" info about API url that this issue requires.

**Comment by kaglowka** [comment]
I suggest using Mailgun Heroku add-on: https://elements.heroku.com/addons/mailgun

How about using a single endpoint for both popup and context menu annotation requests?

**Comment by kaglowka** [comment]
Just i case -- I mean -- in one of them `range` will simply be empty.

**Comment by glowka** [comment]
Yep, perfect for optional arg :)
