### ISSUE TITLE
Make "add annotation" and "add annotation request" more visible in popup

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#251]
An improvement over #233 

![image](https://user-images.githubusercontent.com/6314663/49046674-3091f500-f1d5-11e8-92f2-3eda899a29f4.png)

**Comment by glowka** [comment]
Hey @KasiaSkowronska , for me question mark resemble "help" here. Can you propose alternative version?

**Comment by KasiaSkowronska** [comment]
That was an old mockup, in current version there is no question mark -- I've replaced it with home icon and moved it to the top (the reason for that is that it is significantly less important then other buttons). This home icon is still not perfect, but I couldn't find anything better - we can discuss it on Wednesday.

**Comment by glowka** [comment]
OK, I am happy to hear you have already modified it :)
