### ISSUE TITLE
Add handling &nbsp; in annotation location.

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#258]
The original text may contain `&nbsp;` instead of spaces and consequently they are not located.

Example: https://www.polityka.pl/tygodnikpolityka/kraj/1774718,1,sluzby-w-sluzbie-partii.read?src=mt

**Comment by glowka** [comment]
It might WP plugin issue caused by incorrect or incomplete transformation of HTML entities to UTF8.

Are there any other entities in the text or nbsp is the only case?
