### ISSUE TITLE
Handle unlocated range annotaitons as not located

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#284]
Annotations located by quote are handled in case of location failure, but range annotations are still not.

E.g. at the moment of writing, the problem can be seen here: https://www.polskieradio.pl/7/129/Artykul/2179265

Consequently they won't be displayed in any summaries / counts (in popup and badge)

**Comment by kaglowka** [comment]
I gave it a try, but it cannot be easily improved at all now as of 0.5.0-alpha -- I've added it to my list of things to take into account in the next major application refactor:
https://app.nuclino.com/Przypis-Powszechny-pp/Roboczy/KG-do-uwzgldnienia-przy-refactorze-13f2f62f-b1ad-445c-b89c-594d4f04f719

**Comment by glowka** [comment]
> Annotations located by quote are handled in case of location failure, but range annotations are still not.

What does _handle_ mean in this context? In other words, what is current behavior for finding location failure?

>  I've added it to my list of things to take into account in the next major application refactor

Looks like a typical issue, how about storing it on github?

**Comment by kaglowka** [comment]
I created the pending issue list in #291

**Comment by glowka** [comment]
You can even use "Pin issue" option (bottom of right panel on issue page) if it is kind refactor list _singleton_ :D

**Comment by kaglowka** [comment]
Currently all annotations are located using `quote` rather than range (range is used only as an intermediary between `quote` and the resulting HTML highlighting).

This issue is now outdated.
