### ISSUE TITLE
Replace annotation form

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#324]
- [x] move Editor to the new side widget
- [x] update form
    - [x] fields in mockup
    - [x]  send annotation request id
- [x] remove adding annotation from context menu

Blocked by https://github.com/PrzypisPowszechny/pp/issues/119

Requires backend changes: https://github.com/PrzypisPowszechny/pp/issues/124

![img_1077](https://user-images.githubusercontent.com/5549304/57288517-e41edf80-70b9-11e9-8ac3-1ee820e26f38.jpg)

**Comment by kaglowka** [comment]
@KasiaSkowronska

**Comment by glowka** [comment]
Useful link with store schema: https://gist.github.com/glowka/a067a0c17bf31495f80a7b4f1397496e
