### ISSUE TITLE
Annotation validation

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp-client#87]
This issue is a bit related to #80, #81 (changes from mockup przypis.png in  https://drive.google.com/drive/folders/1nRHmCbhhdxqjfymR65KRiPi1nOdVKxTG) but also some more general observations while working on that.

I would like to find solutions for following questions:
1. Shall we apply simple url format validation to assure most basic mistake wasn't made?
2. Shall we require user to add at least X letters long comment if any comment given to avoid few word comments?
3. Is "źródło" new annotation type or fallback type when no comment is given (which might be kind of surprising for user)?
4. What is the max length of title? Currently no supplied so there is just silent error when title is longer than backend can handle (which is a random, pretty unreasonable length, I guess).

@kaglowka @KasiaSkowronska can you help?

**Comment by kaglowka** [comment]
1. Yes, we were planning to talk tomorrow about URL prefixing with `http` / `www` (if needed) and, besides, URL validation. I'm opening an issue right away.
2. I'm not sure this approach is a real improvement - if a user is malicious, they can always eacily exceed the limit. We assume the annotations will be moderated anyway (in the weakest form -- they can be rolled back and users can be banned). At the same time, I think it can be confusing for a user to find out that an actual character limit exists. One use case I'm thinking of is when the user saves an annotation by accident -- how about a modal asking "Are you sure you want to submit that annotation?". I think that would resolve the problem without confusing the user.
3. While removing the "comment" field altogether from layout is well-founded on our UX test observations, I agree the type change can be confusing. Let's leave it as it is, talk it over tomorrow and change it if most of us share that confusion.
4. I just experimented and I think 110 chars is a nice threshold.

Let's talk these issues over tomorrow. For now, I'm opening an issue for the most obvious -- 1 and 4.

**Comment by glowka** [comment]
> 2. I'm not sure this approach is a real improvement - if a user is malicious, they can always eacily exceed the limit. We assume the annotations will be moderated anyway (in the weakest form -- they can be rolled back and users can be banned). At the same time, I think it can be confusing for a user to find out that an actual character limit exists. One use case I'm thinking of is when the user saves an annotation by accident -- how about a modal asking "Are you sure you want to submit that annotation?". I think that would resolve the problem without confusing the user.

My intention, of course, wasn't to prevent malicious actions, rather to give some kind of suggestion to the user that if he or she decides to add comment it should be longer. My solution proposed here is obviously very rough, but it would be nice to provide user with information about comment without leaving form.
So I would definitely avoid extending modal, actually I would be rather inclined to replace it with something softer or at least make the overlay more transparent to achieve dialog-like appearance when the previous form is still in sight and you don't lose your sense of orientation.

> 3. While removing the "comment" field altogether from layout is well-founded on our UX test observations, I agree the type change can be confusing. Let's leave it as it is, talk it over tomorrow and change it if most of us share that confusion.

Yeah, let's talk it over or for me you guys @kaglowka and @KasiaSkowronska can even take this point into account and provide any solution you find best,  but let me stress that choosing type in one form and than having it explicitly ignored and overridden is AFAIK not an option for any UX.

>  opened two different issues, and referenced this one, as none really felt more related to this issue than the other. Do you think there is some more to do here, or we should close this issue?

I'd prefer to keep it open to track the remaining issues until for each one we make proper decision to work on it or drop it.

**Comment by glowka** [comment]
So

2. We didn't even talk about it, so I assume it is not a priority - dropped.
3. We will work on that in the future as we plan major redesign of the interface in the incoming iterations
